name: IsoNimCocoa
options:
  bundleIdPrefix: com.metacraft.isonim
  deploymentTarget:
    iOS: "17.0"
    macOS: "14.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true

settings:
  base:
    DEVELOPMENT_TEAM: GK3D7BH967

targets:
  IsoNimCocoa-Native:
    type: application
    platform: iOS
    sources:
      - path: ios-app/Sources
    settings:
      base:
        INFOPLIST_FILE: ios-app/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.metacraft.isonim.cocoa.native
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: THEME_NATIVE
        PRODUCT_NAME: "Tasks Native"
        PRODUCT_MODULE_NAME: IsoNimCocoa_iOS
    dependencies: []

  IsoNimCocoa-Branded:
    type: application
    platform: iOS
    sources:
      - path: ios-app/Sources
    settings:
      base:
        INFOPLIST_FILE: ios-app/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.metacraft.isonim.cocoa.branded
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: THEME_BRANDED
        PRODUCT_NAME: "Tasks IsoNim"
        PRODUCT_MODULE_NAME: IsoNimCocoa_iOS
    dependencies: []

  IsoNimCocoa-Tests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: ios-app/Tests
    settings:
      base:
        INFOPLIST_FILE: ios-app/Tests/Info.plist
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Tasks Native.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Tasks Native"
        BUNDLE_LOADER: "$(TEST_HOST)"
    dependencies:
      - target: IsoNimCocoa-Native

schemes:
  Native:
    build:
      targets:
        IsoNimCocoa-Native: all
        IsoNimCocoa-Tests: [test]
    test:
      targets:
        - IsoNimCocoa-Tests
  Branded:
    build:
      targets:
        IsoNimCocoa-Branded: all
    test:
      targets: []
